default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  database: chat_app_challenge_development
  username: <%= ENV.fetch("PG_USERNAME", "postgres") %>
  password: <%= ENV.fetch("PG_PASSWORD", "dev2023") %>
  host:     <%= ENV.fetch("PG_HOST", "localhost") %>
  port:     <%= ENV.fetch("PG_PORT", 5432) %>

test:
  <<: *default
  database: chat_app_challenge_test

production:
  <<: *default
  database: chat_app_challenge_production
  url: <%= ENV['DATABASE_URL'] %>
